# CircleCI Configuration File for Fitness Tracker App

version: 2.1

# Define reusable commands, executors, and jobs
orbs:
  node: circleci/node@4.1.0 # Using Node.js orb for Node.js applications
  android: circleci/android@3.1.0 # Android orb for Android app builds

executors:
  node-executor:
    docker:
      - image: cimg/node:14.17.0 # Specify Node.js version

jobs:
  build-node-app:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages
      - run: npm run build

  test-node-app:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages
      - run: npm test

  build-android-app:
    executor: android/default
    steps:
      - checkout
      - run:
          name: Build Android APK
          command: ./gradlew assembleRelease

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-node-app
      - test-node-app:
          requires:
            - build-node-app
      - build-android-app:
          requires:
            - test-node-app
